### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [sjlawton/proj8#1]
Nice ternaries and use of `begin`-`rescue`! This is also one of the only forms I haven't been able to somehow break. :smiley: 

I do see some unused `.erb` files though, that should be deleted to keep out clutter. And the indentation in `app.rb` is a little wild. Can you fix these with the two resources below?
- [Removing multiple files from a Git repo that have already been deleted from disk](http://stackoverflow.com/questions/492558/removing-multiple-files-from-a-git-repo-that-have-already-been-deleted-from-disk)
- [Ruby indentation](https://github.com/chrisvfritz/tc359_cheatsheets/blob/master/ruby/indentation.md)

Ping me here when that's done and I'll take another look. If you have trouble resolving one, don't hesitate to let me know and I'll be happy to help.

**Comment by sjlawton** [comment]
These issues should be fixed as well.

**Comment by chrisvfritz** [comment]
Excellent work on the `.erb` files. [The Ruby indentation](https://github.com/sjlawton/proj8/blob/master/app.rb) still doesn't look quite right, but as I mentioned in the previous project, [this video](https://www.youtube.com/watch?v=GMf8dlrEbB4) may be able to help with that if you're using Sublime Text.

**Comment by sjlawton** [comment]
OK, both my projects should have fixed indentation now.

**Comment by chrisvfritz** [comment]
:+1: Looks great!
